# Generated by Django 4.1 on 2022-08-21 21:39

from django.db import migrations, models
import django.db.models.deletion
import portal.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=64)),
                ('UniqueID', models.CharField(default='', max_length=50, null=True, unique=True)),
                ('Enable', models.BooleanField(default=False)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventID', models.CharField(default=uuid.UUID('b4b7969d-36c4-4660-beaf-463671b6c84d'), max_length=50, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to=portal.models.scan_upload_to)),
                ('Health', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('Lattitude', models.FloatField(default=0.0)),
                ('Longitude', models.FloatField(default=0.0)),
                ('action', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.device')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to=portal.models.image_upload_to)),
                ('UniqueID', models.CharField(default='', max_length=50, null=True)),
                ('EmiratesID', models.CharField(default='', max_length=16, null=True)),
                ('ContactNo', models.CharField(default='', max_length=13, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Hat', models.BooleanField(default=False)),
                ('Gloves', models.BooleanField(default=False)),
                ('Vest', models.BooleanField(default=False)),
                ('Boot', models.BooleanField(default=False)),
                ('Glasses', models.BooleanField(default=False)),
                ('Mask', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hat', models.BooleanField(default=False)),
                ('Gloves', models.BooleanField(default=False)),
                ('Vest', models.BooleanField(default=False)),
                ('Boot', models.BooleanField(default=False)),
                ('Glasses', models.BooleanField(default=False)),
                ('Mask', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('EventID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.event')),
            ],
        ),
        migrations.CreateModel(
            name='HealthScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('IDn', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('Mobile', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('CodeType', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('Typex', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('Category', models.IntegerField(default=0)),
                ('GenTime', models.DateTimeField(null=True)),
                ('ExpTime', models.DateTimeField(null=True)),
                ('DPIDate', models.DateTimeField(null=True)),
                ('PCRDate', models.DateTimeField(null=True)),
                ('DPIResult', models.CharField(blank=True, max_length=20, null=True)),
                ('PCRResult', models.CharField(blank=True, max_length=20, null=True)),
                ('Excemption', models.BooleanField(default=False)),
                ('Junior', models.BooleanField(default=False)),
                ('Senior', models.BooleanField(default=False)),
                ('Vaccinated', models.BooleanField(default=False)),
                ('Visitor', models.BooleanField(default=False)),
                ('Volunteer', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('EventID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='Person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.personnel'),
        ),
        migrations.AddField(
            model_name='event',
            name='Rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.rule'),
        ),
    ]
