# Generated by Django 4.1 on 2022-08-21 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='processed',
            new_name='healthprocessed',
        ),
        migrations.AddField(
            model_name='event',
            name='safetyprocessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventID',
            field=models.CharField(default=uuid.UUID('57d7d7f5-3f71-4d9a-a7a2-158bed6a58b4'), max_length=50, null=True),
        ),
    ]
