# Generated by Django 4.1 on 2022-08-21 23:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_processed_event_healthprocessed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventID',
            field=models.CharField(default=uuid.UUID('d8248468-d37c-4291-a8b5-8186f577d49d'), max_length=50, null=True),
        ),
    ]
