# Generated by Django 4.1 on 2022-08-21 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_event_eventid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='healthprocessed',
        ),
        migrations.AddField(
            model_name='event',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventID',
            field=models.CharField(default=uuid.UUID('c036cd9f-212d-4d58-9c7c-4c54632a96ed'), max_length=50, null=True),
        ),
    ]
