# Generated by Django 4.1 on 2022-08-21 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_event_healthprocessed_event_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='safetyprocessed',
        ),
        migrations.AlterField(
            model_name='event',
            name='EventID',
            field=models.CharField(default=uuid.UUID('51e03eeb-e559-48f4-946a-5f51ff23a9a7'), max_length=50, null=True),
        ),
    ]
