# Generated by Django 4.1 on 2022-08-21 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_event_safetyprocessed_alter_event_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='healthprocessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='safetyprocessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventID',
            field=models.CharField(default=uuid.UUID('1b740539-b9fe-4941-b470-aebb3f706829'), max_length=50, null=True),
        ),
    ]
