# Generated by Django 4.1 on 2022-08-22 01:11

from django.db import migrations, models
import portal.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_event_healthprocessed_event_safetyprocessed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyscan',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.processed_image_upload_to),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventID',
            field=models.CharField(default=uuid.UUID('55dff854-39f7-49bd-adc7-e5367fe03b81'), max_length=50, null=True),
        ),
    ]
